# app custom Makefile

# Docker repo & image name without version
IMAGE     ?= plausible/analytics
# Docker image version
IMAGE_VER ?= v1.5
# Hostname for external access
APP_SITE  ?= plau.dev.lan
# App names (db/user name etc)
APP_NAME  ?= plau

# Enable DB usage:
# * Add DB config part to .env.sample
# * Enable db* targets
# * make db-create inside .drone-default target
USE_DB    ?= yes

# ------------------------------------------------------------------------------
# app custom config

# The hosting URL of the server, used for URL generation.
BASE_URL              ?= $(HTTP_PROTO)://$(APP_SITE)

# An internal secret key used by Phoenix Framework
SECRET_KEY_BASE       ?= $(shell openssl rand -base64 64 | tr -d '\n' ; echo)

# Restricts registration of new users.
# Possible values are true (full restriction), false (no restriction), and invite_only (only the invited users can register).
DISABLE_REGISTRATION  ?= false

# The email id to use for as from address of all communications from Plausible.
MAILER_EMAIL          ?= hello@plausible.local
# The host address of your smtp server.
SMTP_HOST_ADDR        ?= localhost
# The port of your smtp server.
SMTP_HOST_PORT        ?= 25
# The username/email in case SMTP auth is enabled.
SMTP_USER_NAME        ?= user
# The password in case SMTP auth is enabled.
SMTP_USER_PWD         ?= password
# If SSL is enabled for SMTP connection
SMTP_HOST_SSL_ENABLED ?= false
# Number of retries to make until mailer gives up.
SMTP_RETRIES          ?= 2

# Path to /opt/dcape/var. Used by clickhouse
DCAPE_ROOT           ?= /opt/dcape/var

# ------------------------------------------------------------------------------
# .env template (custom part)
# inserted in .env.sample via 'make config'
define CONFIG_CUSTOM
# ------------------------------------------------------------------------------
# app custom config, generated by make config
# db:$(USE_DB) user:$(ADD_USER)

# The hosting URL of the server, used for URL generation.
BASE_URL=$(BASE_URL)

# An internal secret key used by Phoenix Framework
SECRET_KEY_BASE=$(SECRET_KEY_BASE)

# Restricts registration of new users.
# Possible values are true (full restriction), false (no restriction), and invite_only (only the invited users can register).
DISABLE_REGISTRATION=$(DISABLE_REGISTRATION)

#RELEASE_DISTRIBUTION=none

# HTTP proto (based on USE_TLS)
#HTTP_PROTO=$(HTTP_PROTO)

# The email id to use for as from address of all communications from Plausible.
MAILER_EMAIL=$(MAILER_EMAIL)
# The host address of your smtp server.
SMTP_HOST_ADDR=$(SMTP_HOST_ADDR)
# The port of your smtp server.
SMTP_HOST_PORT=$(SMTP_HOST_PORT)
# The username/email in case SMTP auth is enabled.
SMTP_USER_NAME=$(SMTP_USER_NAME)
# The password in case SMTP auth is enabled.
SMTP_USER_PWD=$(SMTP_USER_PWD)
# If SSL is enabled for SMTP connection
SMTP_HOST_SSL_ENABLED=$(SMTP_HOST_SSL_ENABLED)
# Number of retries to make until mailer gives up.
SMTP_RETRIES=$(SMTP_RETRIES)

DCAPE_ROOT=$(DCAPE_ROOT)

endef

# ------------------------------------------------------------------------------
# Find and include DCAPE/apps/drone/dcape-app/Makefile
DCAPE_COMPOSE   ?= dcape-compose
DCAPE_MAKEFILE  ?= $(shell docker inspect -f "{{.Config.Labels.dcape_app_makefile}}" $(DCAPE_COMPOSE))
ifeq ($(shell test -e $(DCAPE_MAKEFILE) && echo -n yes),yes)
  include $(DCAPE_MAKEFILE)
else
  include /opt/dcape-app/Makefile
endif

# -----------------------------------------------------------------------------
## Custom app targets
#:

## create clickhouse db
events-db-create: CMD=exec events_db clickhouse-client --query "CREATE DATABASE IF NOT EXISTS plausible_events_db"
events-db-create: dc

